export interface GeniusSong {
    annotation_count: number;
    api_path: string;
    apple_music_id: string | null;
    apple_music_player_url: string | null;
    artist_names: string;
    description?: Record<string, unknown>; 
    embed_content: string;
    featured_video: boolean;
    full_title: string;
    header_image_thumbnail_url: string;
    header_image_url: string;
    id: number;
    language: string;
    lyrics_owner_id: number;
    lyrics_state: string;
    path: string;
    primary_artist_names: string;
    pyongs_count: number | null;
    recording_location: string | null;
    relationships_index_url: string | null;
    release_date: string | null;
    release_date_for_display: string | null;
    release_date_with_abbreviated_month_for_display: string | null;
    song_art_image_thumbnail_url: string;
    song_art_image_url: string;
    stats?: Record<string, unknown>;
    title: string;
    title_with_featured: string;
    url: string;
    current_user_metadata?: Record<string, unknown>; 
    song_art_primary_color?: string | null;
    song_art_secondary_color?: string | null;
    song_art_text_color?: string | null;
    album?: Record<string, unknown>;
    custom_performances?: Array<Record<string, unknown>>; 
    description_annotation?: Record<string, unknown>; 
    featured_artists?: Array<Record<string, unknown>>;
    lyrics_marked_complete_by?: string | null;
    lyrics_marked_staff_approved_by?: string | null;
    media?: Array<Record<string, unknown>>; 
    primary_artist?: Record<string, unknown>; 
    primary_artists?: Array<Record<string, unknown>>;
    producer_artists?: Array<Record<string, unknown>>; 
    song_relationships?: Array<Record<string, unknown>>; 
    translation_songs?: Array<Record<string, unknown>>; 
    verified_annotations_by?: Array<Record<string, unknown>>; 
    verified_contributors?: Array<Record<string, unknown>>; 
    verified_lyrics_by?: Array<Record<string, unknown>>;
    writer_artists?: Array<Record<string, unknown>>; 
  }
  